name: Django Collectstatic
author: Samuel Abels <knipknap@gmail.com>
description: A GitHub Action that collects staticfiles und minifies them
inputs:
  requirements:
    description: Full path to requirements.txt (including filename)
    required: true
  manage_py_dir:
    description: Directory to manage.py (relative to repository root)
    required: true
  static_out_dir:
    description: Directory containing the static files (relative to repository root)
    required: true
  static_in_dir:
    description: >
      Directory into which the static files are written (relative to repository root).
      MUST be different from source!
    required: true

runs:
  using: docker
  image: Dockerfile

branding:
  icon: send
  color: green
