name: Example usage

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Start Deployment
      uses: knipknap/django-collectstatic@master
      with:
        requirements: example/requirements.txt
        manage_py_dir: example/
        static_in_dir: example/static/
        static_out_dir: example/static-out/
